"""State-carrier trace and paper-only trajectory scatter, generated from results."""
import json


def widget(results):
    if not isinstance(results, dict) or results.get('lab_kind') != 'forgetting05':
        return ''
    data = json.dumps(results, ensure_ascii=False).replace('<', '\\u003c')
    return r'''<section class="forget05" aria-label="状態の保存先と再導出">
<style>
.forget05{--f:#336a65;background:#f1f5f2;padding:clamp(12px,3vw,28px);border-radius:16px;color:#163a38}.forget05 *{box-sizing:border-box}.forget05 .carriers{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:20px 0}.forget05 .carrier{background:white;border-top:4px solid var(--f);padding:14px;border-radius:6px}.forget05 select,.forget05 input{max-width:100%;font:inherit}.forget05 select{width:100%;padding:10px}.forget05 .trace{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:16px 0}.forget05 .step{padding:10px;background:white;border-left:4px solid #64847b}.forget05 .step.lost{border-color:#b55634;background:#fff2e9}.forget05 .step.disk{border-color:#346eb1}.forget05 svg{width:100%;height:auto;background:white;border-radius:8px}.forget05 .equation{padding:15px;background:white;font-family:monospace;overflow-wrap:anywhere}.forget05 figcaption{font-size:.9rem}.forget05 label{display:block;margin:12px 0}.forget05 output{font-weight:700}.forget05 .risk{display:flex;gap:14px;flex-wrap:wrap}.forget05 .risk p{flex:1;min-width:160px;padding:12px;background:#fff}.forget05 .risk strong{display:block;font-size:1.8rem}@media(max-width:600px){.forget05 .carriers,.forget05 .trace{grid-template-columns:1fr}.forget05 svg text{font-size:15px}}
</style>
<h3>必要な制約は、どこに残っているか</h3>
<div class="carriers"><div class="carrier"><b>推論 R</b><p>まだ実行していない計画・制約・中間結論</p></div><div class="carrier"><b>コード / ファイル Z</b><p>導いた結果を保存。後続の判断で読めることが条件</p></div><div class="carrier"><b>観測 O</b><p>tool出力・stderr。再取得せず使える証拠</p></div></div>
<p>左から右への移動は自動ではない。保存と読出しを終えて初めて、推論以外から状態を復元できる。</p>
<label>同じ6要求に与える履歴<select data-case><option value="keep">推論を保持する</option><option value="prune_internal">推論だけを削る</option><option value="prune_external">ファイルへ保存してから削る</option><option value="prune_unreadable">保存したが、ファイルを読めない</option></select></label>
<div class="trace" data-trace></div><p data-summary aria-live="polite"></p>
<p>参照1・読出し2・再導出10の人工労力。LLMや実token数の測定ではない。全条件で最終値は同じ。</p>
<h3>観察的な状態比較：31課題から265境界</h3><div class="risk" data-risk></div>
<p>Table 14の著者報告。同一task内差は19.75ポイント [1.00, 37.05]（Table 15）。群全体の差31.16ポイントと区別する。無作為な外部化の効果ではない。</p>
<figure><h3>多く削っても、作業全体の節約が増えるとは限らない</h3><svg viewBox="0 0 560 330" role="img" aria-label="Random削除率と入力削減率の散布図" data-scatter></svg><figcaption>著者報告 Table 10 / Fig. 3。80課題でのRandom token削除だけを表示。点をつなぐ曲線や最適削除率は推定していない。</figcaption></figure>
<h3>小さな行動分布差も、長い作業では累積する</h3><label>共通履歴での差の上限 ε <input data-e type="range" min="0" max="0.1" step="0.005" value="0.02"></label><label>行動回数 K <input data-k type="range" min="1" max="100" value="30"></label><div class="equation" data-bound aria-live="polite"></div><p>Theorem B.3の仮定を置いた上界。実測リスクではなく、entropyからεを推定する式でもない。</p>
<script type="application/json" data-forget>''' + data + r'''</script>
<script>(()=>{const root=document.currentScript.parentElement,d=JSON.parse(root.querySelector('[data-forget]').textContent),sel=root.querySelector('[data-case]');function show(){const c=d.cases[sel.value],names={'reasoning':'推論を参照','read-file':'ファイルを読む','rederive':'制約を導き直す'};root.querySelector('[data-trace]').innerHTML=c.trace.map((t,i)=>`<div class="step ${t.action==='rederive'?'lost':t.action==='read-file'?'disk':''}"><b>${i+1}. ${t.key}</b><br>${names[t.action]}<br>値 ${t.value} ／ 労力 ${t.effort}</div>`).join('');root.querySelector('[data-summary]').textContent=`再導出 ${c.rederivations}回 ／ 読出し ${c.file_reads}回 ／ 人工労力 ${c.effort_units}`;}sel.addEventListener('change',show);show();root.querySelector('[data-risk]').innerHTML=d.paper.risk.map(x=>`<p>${x.group}<strong>${x.percent}%</strong>n=${x.n}境界</p>`).join('');const x=v=>65+v*10,y=v=>265-v*3;let s='<text x="65" y="23">入力削減率 %（大きいほど節約）</text><path d="M65 45 V265 H500" fill="none" stroke="#456"/>';[0,20,40,60].forEach(v=>s+=`<text x="25" y="${y(v)+5}">${v}</text><path d="M65 ${y(v)}H500" stroke="#ddd"/>`);[0,10,20,30,40].forEach(v=>s+=`<text x="${x(v)-7}" y="287">${v}</text>`);d.paper.random.forEach(p=>s+=`<circle cx="${x(p.delete)}" cy="${y(p.input_reduction)}" r="7" fill="#b55634"/><text x="${x(p.delete)+9}" y="${y(p.input_reduction)-10}">${p.input_reduction}%</text>`);s+='<text x="150" y="318">その場で削る推論tokenの割合 %</text>';root.querySelector('[data-scatter]').innerHTML=s;function bound(){let e=+root.querySelector('[data-e]').value,k=+root.querySelector('[data-k]').value;root.querySelector('[data-bound]').textContent=`ε=${e.toFixed(3)}, K=${k} → TV ≤ 1−(1−ε)^K = ${(1-(1-e)**k).toFixed(3)} ≤ min(1,Kε) = ${Math.min(1,k*e).toFixed(3)}`;}root.querySelector('[data-e]').addEventListener('input',bound);root.querySelector('[data-k]').addEventListener('input',bound);bound();})();</script></section>'''
